name: Prebuild Binaries

on:
  push:
    branches:
      - deploy
      - deploy-alpha

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - uses: actions/checkout@v3
      - run: npm install --ignore-scripts --no-audit --no-save
      - run: npx node-pre-gyp rebuild package testpackage
      - run: npm test
      - run: node --expose-gc ./scripts/test-memory-leaks.js

  prebuild:
    needs: test
    strategy:
      matrix:
        node-version: ["12.13.0", "14.13.0", "16.0.0", "18.0.0", "19.0.0", "20.0.0"]
        os: [ubuntu-latest, macos-latest, windows-2019]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - uses: actions/checkout@v3
      - run: npm install --ignore-scripts --no-audit --no-save
      - run: npx node-pre-gyp rebuild package testpackage
      - run: npm test
      - name: Prebuild
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.PREBUILD_GITHUB_TOKEN }}
        run: node scripts/node-pre-gyp-publish.js
