name: Prebuild Binaries

on:
  push:
    branches:
      - deploy

jobs:
  prebuild-linux:
    name: Linux
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - run: sudo apt-get install g++-multilib
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
      - run: npm i -g node-gyp@latest
      - run: npm install
      - run: npm test
      - run: node --expose-gc ./scripts/test-memory-leaks.js
      - name: Prebuild
        env:
          PREBUILD_GITHUB_TOKEN: ${{ secrets.PREBUILD_GITHUB_TOKEN }}
        run: node ./scripts/prebuild

  prebuild-macos:
    name: macOS
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
      - run: npm i -g node-gyp@latest
      - run: npm install
      - run: npm test
      - run: node --expose-gc ./scripts/test-memory-leaks.js
      - name: Prebuild
        env:
          PREBUILD_GITHUB_TOKEN: ${{ secrets.PREBUILD_GITHUB_TOKEN }}
        run: node ./scripts/prebuild

  prebuild-windows:
    name: Windows
    runs-on: windows-2019
    timeout-minutes: 15
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
      - run: npm i -g node-gyp@latest
      - run: npm install
      - run: npm i node-gyp@latest
      - run: npm test
      - run: node --expose-gc ./scripts/test-memory-leaks.js
      - name: Prebuild
        env:
          PREBUILD_GITHUB_TOKEN: ${{ secrets.PREBUILD_GITHUB_TOKEN }}
        run: node ./scripts/prebuild
